### ISSUE TITLE
極めて長いcodeをスクロールもしくは改行するべきか

### ISSUE THREAD

**Issue by yumetodo** [increments/mastodon#102]
C++をやっていると

`std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>> std::list<_Ty,std::allocator<_Ty>>::emplace<std::stack<KeyState::binded_key_event_t,std::deque<std::function<void (void)>,std::allocator<std::function<void (void)>>>>>(std::_List_const_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,std::stack<KeyState::binded_key_event_t,std::deque<std::function<void (void)>,std::allocator<std::function<void (void)>>>> &&)`

のような長い~~型~~シグネチャに遭遇することがあり、これをTooTしたくなったとする。

ex.) https://qiitadon.com/@yumetodo/99348929727200663

しかし、`overflow: hidden;`になっているので、表示しきれない。

スクロールもしくは改行するべきではないか？

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tomoasleep** [comment]
インラインだとスクロールしにくいので、改行した方が良さそうですね。

インラインのコードも `white-space: pre` になっているのを `white-space: pre-wrap` にしようと思います。(下画像のような表示になります。)

<img width="698" alt="2018-01-29 13 21 50" src="https://user-images.githubusercontent.com/1477130/35493557-b3119cea-04f7-11e8-84f5-b879294fda49.png">

※追記
`word-break: break-all` も有効にする

<img width="783" alt="2018-01-29 13 30 42" src="https://user-images.githubusercontent.com/1477130/35493709-aa8b1280-04f8-11e8-8ac1-89b72f29bfd6.png">
