### ISSUE TITLE
LTL 上で返信の付いているトゥートがわかるようにして欲しい

### ISSUE THREAD

**Issue by KEINOS** [increments/mastodon#111]
スレッドになっている、つまり返信のあるトゥートがタイムライン上で確認できると嬉しいです。

本家の [issue #731 「UI suggestion: Indicate in-line when a post has replies」](https://github.com/tootsuite/mastodon/issues/731) にも挙がっているのですが、Qiitadon にも要望として挙げたいと思います。

### 難しさ

返信トゥート自身は `status` に [`in_reply_to_id`](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#status) を持っているので `in_reply_to_id !== null` で自身が返信である旨をアイコン化できているのだ思います。

逆に、自身が親トゥートである、つまり「返信が付いている = スレッドである」という情報が `status` にないため、一旦 DB を舐めないといけないのが大変そうです。

### 自分の案

言うがやすしだと思うのですが、 TL 上のトゥートを描画する際に返信トゥートであった場合（ `in_reply_to_id` がある場合）は、親トゥートの ID を配列に入れておき、自身のトゥート ID が配列にマッチしたら「返信」ボタンのアイコンを変えると言うのはどうでしょう？

描画のタイミングなども難しそうですが。

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unasuke** [comment]
ref https://github.com/tootsuite/mastodon/issues/731#issuecomment-423049956

>I think this is solved now, with both the "is a reply" iconography and the "0", "1", and "1+" indicators next to the "reply" button.


とのことなので、Qiitadonが2.5.0くらいまで上がれば解決すると思います

**Comment by KEINOS** [comment]
@unasuke 

おぉ、情報ありがとうございます！では、本 issue は Close いたします！
