### ISSUE TITLE
Liveness of this project

### ISSUE THREAD

**Issue by kojix2** [increments/mastodon#122]
このプロジェクトのコミット権を持つ方はどなたですか？

**Comment by kojix2** [comment]
![comitter](https://user-images.githubusercontent.com/5798442/118358373-6f8cae80-b5b9-11eb-9ede-d8d7ae2e3b7f.png)

**Comment by yoshi389111** [comment]
僭越ながらコミッターのスペルはcommitterです

**Comment by KEINOS** [comment]
もぅ、committer ちゃんなんだからっ

**Comment by kojix2** [comment]
ﾈｺ
