### ISSUE TITLE
ホーム画面の各カラムの横幅が小さい

### ISSUE THREAD

**Issue by tomoasleep** [increments/mastodon#30]
横幅が小さく、コードを表示する場合には十分でない。

<img width="334" alt="2017-05-29 14 42 04" src="https://cloud.githubusercontent.com/assets/1477130/26537767/09decafc-447d-11e7-9102-f53d494d4a60.png">

**Comment by htomine** [comment]
横幅広げた体験、Mastodonぽくなさそうだけどその辺をどう考えるかという気はしますね。
テーマ変えてる時点で…ではあるが。

**Comment by tomoasleep** [comment]
試しに伸ばすようにしたコード書いてみたけどディスプレイ次第でめっちゃ伸びてヤバい
![2017-05-29 10 28 24](https://cloud.githubusercontent.com/assets/1477130/26539951/009d210c-448a-11e7-8fc2-e960e9989f16.png)

**Comment by htomine** [comment]
@tomoasleep みずちのこれよさそうなのでちょっちやってみます。
https://qiitadon.com/@mizchi/145

**Comment by kagua** [comment]
Chrome拡張でCSSで伸ばす、というコードは出回ってまわってるようですが、それではダメですかね。

**Comment by htomine** [comment]
以下の方針を採用させていただく形でいこうかなと :pray:

https://qiitadon.com/@voqn/742

> Qiitaの場合、メインカラムとみなすカラム横幅を拡大すれば個別のトゥートで拡大できるんで、PCの場合、以下で必要十分だと思う

```
@media screen and (min-width: 1025px) {
    .columns-area>div:last-child>.column,
    .mastodon-column-container>.column {
        flex: 1;
        max-width: 640px; /* ← これは好み */
     }
}
```

以下のように、最も右のカラムが残りの画面幅分広くなる。みたいコードをクリックすればここに拡張されて表示されるし、ローカルタイムライン等のコードも広めにみれる。
![image](https://cloud.githubusercontent.com/assets/732828/26551420/6d23a6d8-44bd-11e7-83e7-40953fbf9119.png)
