### ISSUE TITLE
通知欄でユーザー名にカーソルを合わせると消えたように見える

### ISSUE THREAD

**Issue by yoshiken** [increments/mastodon#33]
おそらくDark配色時の仕様で白強調されてしまい背景と同化している

![2017-05-29 16 42 31](https://cloud.githubusercontent.com/assets/7807989/26540759/d981f0ee-448d-11e7-8b93-99b57b5029cb.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by VoQn** [comment]
here.
https://github.com/increments/mastodon/blob/qiitadon/app/assets/stylesheets/components.scss#L927
dark-theme, light-theme 共に↓ のセレクタを指定していなかったので、上書きしていなかったようです

```scss
.notification__display-name:hover {
   color: $color5;
}
```

オリジナルの `$color5` は `#ffffff` なので、ついでに components.scss 内で他に文字色として当てられているかを検索しておいて、一通り上書きするように指定すると類似の現象の二度手間が防げるかもしれません
