### ISSUE TITLE
外部インスタンスでコードブロックを含んだトゥートを正しく表示できない

### ISSUE THREAD

**Issue by tomoasleep** [increments/mastodon#35]
# WHAT

Mastodonの仕様として、特定のタグ以外を消してしまうため、`<code>` タグを含んだトゥートが正しく表示できない。

# 報告元

- https://pawoo.net/@ykzts/16179221
- https://pawoo.net/@ykzts/16180366

**Comment by htomine** [comment]
https://mstdn.jp/@Stocker_jp/15674730

**Comment by tomoasleep** [comment]
> https://mstdn.jp/@Stocker_jp/15674730

@htomine これは関係ないです。他のインスタンスのアカウントを見る場合、全てのトゥートを見れないのは仕様です。

**Comment by htomine** [comment]
@tomoasleep ic :oops:

**Comment by tomoasleep** [comment]
https://github.com/increments/mastodon/pull/42 でコードブロックでpreタグを使うのをやめるようにした。
codeタグは残っているけど、Mastodonの利用しているSanitizeライブラリ(https://github.com/rgrove/sanitize)は、codeタグは消しても中身のテキストは消さないので、崩れずに表示されるはず。

(Mastodonでトゥートを表示する際はpre-wrapで空白を詰めないようにしているので空白は置換しなくても取り敢えずMastodonでは崩れない)

**Comment by tomoasleep** [comment]
対策したのでひとまずCloseします。
