### ISSUE TITLE
新規登録後の「メールアドレスの確認」メールが送られてこない

### ISSUE THREAD

**Issue by kanakogohzu** [increments/mastodon#44]
- 新規登録後に```noreply@qiitadon.com```から送られてくる「メールアドレスの確認」メールが送られてこない
 - 迷惑メールにも入っていない

## 対応
- メール再送 

## REF 
https://qiitadon.com/@tomomi/4685

**Comment by tomoasleep** [comment]
メール再送は https://qiitadon.com/auth/confirmation/new から自分のメールアドレスを入力して貰えばユーザー自身で出来ます。
あとは別の手段として管理者はユーザーのメール確認のフラグを確認済みに変更できるのでそちらを使う手もあります。

**Comment by kanakogohzu** [comment]
@tomoasleep ありがとうございます 🙏  https://qiitadon.com/auth/confirmation/new をご案内します 🙇  🙇

**Comment by tomoasleep** [comment]
自分のメールアドレスは https://qiitadon.com/auth/edit から確認できるのでそちらでメールアドレスが正しいか確認してもらうと良さそう

**Comment by kanakogohzu** [comment]
解決しました 👍  ありがとうございます！
メール周りの様子もわかった 😄
