### ISSUE TITLE
バッククオートに囲まれた \1 が消える

### ISSUE THREAD

**Issue by scivola** [increments/mastodon#59]
コードを示すためのバッククオート囲みの中に `\1` と書いても表示されません。

**Comment by yumetodo** [comment]
```
https://github.com/increments/mastodon/issues/59
ふーん・・・
`\1`
こうか
```

Qiitadon
![image](https://user-images.githubusercontent.com/10869046/26955396-6baf33b2-4cf1-11e7-987f-58524affae87.png)
pawoo.net
![image](https://user-images.githubusercontent.com/10869046/26955404-786713f4-4cf1-11e7-8a73-6ba865491499.png)
o.kagucho.net
![image](https://user-images.githubusercontent.com/10869046/26955409-7eba1f08-4cf1-11e7-9bfc-17140afa39ac.png)

ほかのインスタンスから覗くと空行になっている

https://qiitadon.com/@yumetodo/50433

**Comment by scivola** [comment]
原因が分かった気がします。たぶんここです。

https://github.com/increments/mastodon/blob/qiitadon/app/lib/code_block_formatter.rb#L40

置き換えるべき文字列を `sub` の第二引数で与えていますが，置き換え文字列中の `\1` はキャプチャーの参照と解釈されるので，空文字列になってしまうのですね。

試していませんが，

```diff
  def swap_marker_to_code_blocks(html, marker_and_contents)
    marker_and_contents.reverse.reduce(html) do |html, (marker, block_html)|
-      html.sub(marker, block_html)
+      html.sub(marker){block_html}
    end
  end
```

で直るような気が。

**Comment by yumetodo** [comment]
@scivola それだとほかのインスタンスから消えて見えるのは説明できるんでしょうか・・・？

**Comment by scivola** [comment]
@yumetodo あー，じゃあ早とちりかも。
なにしろ直接確かめたわけじゃなくて，コードを追ってたら「これか！」って気がしただけなので。
間違いだったらすいません　＞皆様

**Comment by yumetodo** [comment]
(mastodonのTOOT送信周りの処理がどこにあるかわかっていないの図)

**Comment by yumetodo** [comment]
まあ少なくとも他のインスタンスでは確認できない現象なので、TOOTの送信周りをupstreamとdiffする必要があるかなと。

**Comment by tomoasleep** [comment]
@scivola @yumetodo 報告ありがとうございます。https://github.com/increments/mastodon/pull/60 で修正を行いました。

ちなみに、他のインスタンスが Qiitadon に投稿されたトゥートを表示する場合、Qiitadonが(Formatterで)装飾してhtmlを受け取っていて、それを元に表示しています。(codeタグなどはサニタイズする際に中身を残して消去されますが)
他のインスタンスから見えない現象はこれで説明できます。

**Comment by yumetodo** [comment]
なるほど。ありがとうございます。

**Comment by yumetodo** [comment]
https://qiitadon.com/@tomoasleep/51863
https://qiitadon.com/@yumetodo/52444
修正確認しました。
