### ISSUE TITLE
投票機能が欲しい

### ISSUE THREAD

**Issue by kanakogohzu** [increments/mastodon#63]
## WHY
- わいわいできそう
- Qiitaの新機能実装のアンケートとかやったら面白い
- QiitaのTwitterアカウントでやってもいいけどQiitadonにも欲しい 🔥 

## REF
- http://nagished.com/useful/20151023-twitter-vote/

**Comment by yumetodo** [comment]
http://start.metagovernment.narkive.com/WxMGtEwk/mg-standards-for-voting
OStatus的にはないっぽい・・・？

**Comment by yumetodo** [comment]
>https://pawoo.net/@ykzts/19761126
>https://github.com/tootsuite/mastodon/issues/1629 Mastodonの投票、本家にIssueがありますね。

**Comment by kanakogohzu** [comment]
なるほど教えていただきありがとうございます 🙇   
よくわかっていなかったので勉強になりました！
いつか実装されたらQiitadonにも入れられるといいな 🙏  その時またissue立てます 😸
