### ISSUE TITLE
コード部分に <<a と書くと 2 個目の < 以降が消える

### ISSUE THREAD

**Issue by scivola** [increments/mastodon#78]
バッククオート 1 個もしくは 3  個でコードを表現した箇所に `<<a` という文字列があると，2 個目の `<` 以降が消えるようです。

**Comment by munierujp** [comment]
同じ原因かは分かりませんが、シンタックスハイライト機能を用いてHTMLを書こうとすると、タグ部分が消えてしまいます。
おそらくエスケープ処理まわりがあやしいかと思いますが、原因がMastodon本体のエスケープ処理にあるのか、Qiitadon独自のシンタックスハイライト処理にあるのかは分かりません。
せっかくシンタックスハイライト機能があるので、HTMLもそのまま書けるといいですね。

## 普通に書く
普通に書くと、タグ部分のみ消えてしまいます。

### 入力
````
```html
<strong>強調</strong>
```
````

### 出力
````
強調
````

## 文字参照で書く
以下のように文字参照で書けば消えません。

### 入力
````
```html
&lt;strong&gt;強調&lt;/strong&gt;
```
````

### 出力
````
<strong>強調</strong>
````

**Comment by Yoto** [comment]
どうやら同じ原因のようです。

コードを読んでみましたが、[ここ](https://github.com/increments/mastodon/blob/d43b446587e6fabee041a3d9eb40a76d0ea9de17/app/lib/code_block_formatter.rb#L19)と[ここ](https://github.com/increments/mastodon/blob/d43b446587e6fabee041a3d9eb40a76d0ea9de17/app/lib/code_block_formatter.rb#L29)でコードブロックの内容をsanitizeしてるのが原因のようです。

本家の[このへん](https://github.com/tootsuite/mastodon/blob/e84fecb7e97851ed56f4d954e2d68128bb87da37/app/lib/formatter.rb#L31)を見ても特にsanitizeしてる雰囲気はないので、sanitizeからescapeに切り替えれば解決するのではと思います。

======
以上を[Qiitadonに投稿](https://qiitadon.com/web/statuses/99057563938448351)したのでマルチポストっぽくなってますが、経緯を残すためにGitHubにも投稿しておきます。

**Comment by yumetodo** [comment]
`<meta charset="utf-8">`も[消えます](https://qiitadon.com/@yumetodo/99199824204884788)ねぇ・・・ 、というかまだ治ってなかったのか。

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/34347957-92559bea-ea4a-11e7-9ef3-9f34981da6ef.png)

>422 バリデーションに失敗しました: Textを入力してください

となります

**Comment by yumetodo** [comment]
>https://qiitadon.com/@tomoasleep/99239107735346892
>@tomoasleep
>コード記法Tootに反映されないバグ修正しました。コード記法内でタグ等が書けないバグも併せて直しました 💁
>2017年12月26日 15:10

今度こそ治った
