### ISSUE TITLE
コードブロックに文字を書くと消えちゃう

### ISSUE THREAD

**Issue by pugiemonn** [increments/mastodon#81]
[Issue text goes here].

```
num1 = 10
num2 = 2.0

def pugiemonn():
    print(num1)
    print(type(num1))
    print(num2)
    print(type(num2))
    
pugiemonn()

'''
10
<class 'int'>
2.0
<class 'float'>
'''
```
これをqiitadonに投稿すると文字が消えちゃう
投稿済み: https://qiitadon.com/@pugiemonn/484944

**Comment by ykzts** [comment]
https://github.com/increments/mastodon/issues/78#issuecomment-323980025 既出ではないでしょうか。

**Comment by pugiemonn** [comment]
@ykzts 
ありがとうございます👍 #78 と同じようなのでクローズします
