### ISSUE TITLE
キーボードショートカットで移動した時のスタイルが崩れている

### ISSUE THREAD

**Issue by htomine** [increments/mastodon#97]
![image](https://user-images.githubusercontent.com/732828/33194304-6817e2ee-d112-11e7-845c-cd7c6e42f7be.png)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
#93 と重複していますね。

**Comment by htomine** [comment]
なるほど、 2. の項目ですね :pray:
